name: Semgrep

on:
  push:
  pull_request:

jobs:
  semgrep:
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Semgrep Scan
        run: semgrep scan --config auto .